### PR TITLE
Migrate from the deprecated Bazaar endpoint

### PR DESCRIPTION
**Pull request by Richienb**
Fixes: #379

### CODE REVIEW

**Comment by builder-247** [comment]
Could you also add the ability to specify which items to return and document that? Good work nonetheless.

**Comment by Richienb** [comment]
@builder-247 How should I spec out when a method returns an array when a comma is in a string and an object otherwise?

**Comment by builder-247** [comment]
> @builder-247 How should I spec out when a method returns an array when a comma is in a string and an object otherwise?

You could just spec the array and mention in the description that an object is returned for a single entry

**Comment by Richienb** [comment]
@builder-247 Finished!

**Pull request merged**
