### PR TITLE
Added friends endpoint

### PR DESCRIPTION
**Pull request by pjones123**
not too familiar with how your helpers and stuff works but i'm pretty sure this is right, sorry if not.

### CODE REVIEW

**Comment by builder-247** [comment]
You'll need to add a friends job here: https://github.com/slothpixel/core/blob/master/util/utility.js#L213.

It's also probably a good idea to cache the response, as done here for example https://github.com/slothpixel/core/blob/master/store/buildPlayerStatus.js#L7

**Comment by pjones123** [comment]
> You'll need to add a friends job here: https://github.com/slothpixel/core/blob/master/util/utility.js#L213.
> 
> It's also probably a good idea to cache the response, as done here for example https://github.com/slothpixel/core/blob/master/store/buildPlayerStatus.js#L7

https://github.com/slothpixel/core/blob/4bd8b9027e0fac673315b924d220d3035ca73124/util/utility.js#L237 is this not the friends job?

**Comment by builder-247** [comment]
> > You'll need to add a friends job here: https://github.com/slothpixel/core/blob/master/util/utility.js#L213.
> > It's also probably a good idea to cache the response, as done here for example https://github.com/slothpixel/core/blob/master/store/buildPlayerStatus.js#L7
> 
> https://github.com/slothpixel/core/blob/4bd8b9027e0fac673315b924d220d3035ca73124/util/utility.js#L237
> is this not the friends job?

oof, my bad!

**Review by pjones123 — COMMENTED** [review]
changed to use caching

**Comment by builder-247** [comment]
@pjones123 Can you fix the syntax errors?

**Comment by builder-247** [comment]
Would you have time to finish this?

**Comment by pjones123** [comment]
sure, I'll have a look in the next couple of days

**Review by builder-247 — APPROVED** [review]

**Pull request merged**
