### PR TITLE
Update processGuildData.js

### PR DESCRIPTION
**Pull request by iktucker**
Fixed getLevel function as per issue #36

### CODE REVIEW

**Comment by iktucker** [comment]
Thank you for the input, I replaced ++ operators and camelCased names to comply with lint settings. I also noticed that I had at some point introduced a bug (now fixed) that incorrect handled the level cap. Hopefully the function is now up to par.

**Comment by builder-247** [comment]
I still get some weird values in my tests, e.g. `42425410` xp should produce level 21.47, but instead I get 26.14

**Comment by iktucker** [comment]
Hopefully its fixed, I rewrote the function after getting a better understanding of how the PHP function works. I wrote the below on a commit, but I'm putting it here since I had to do another commit for a lint error.

Test data shows the following relationship between character exp and level:

|Experience|Level|
|---------|----|
|375000|2.5|
|9000|0.09|
|0|0|
|100000000000|100|
|3000000|6.2|
|42425410|21.14|
|43500000|21.5|

Note the following example for determining level (and let me know if I'm mistaken):
Example Character exp = 43,500,000
Cumulative needed to reach integer level: 42,000,000
Level: 21 (checked w/PHP function)
Progress towards next level: 43,500,000 - 42,000,000 = 1,500,000
Progress towards next level (percent) = 1,500,000/3,000,000 = 1/2 = 0.5
Exact Level = 21 + 0.5 = 21.5

**Comment by builder-247** [comment]
Looks like the values are still slightly off - although they are closer now. I tested it by running some leaderboard guilds through it.

**Comment by iktucker** [comment]
Are you pulling the precise levels through the Hypixel API or through a third party utility? I'm unable to source precise guild levels elsewhere, and the outdated plancke php API uses the same method to calculate (player) exact levels as I am using here (level + percent to next).

https://github.com/Plancke/hypixel-php/blob/master/src/util/Leveling.php

Note the getExactLevel() and getPercentageToNextLevel() methods there.

**Comment by builder-247** [comment]
I've noticed the exact level values in https://sk1er.club/leaderboards/guild_level match the ones in `/g info`.

**Pull request merged**
