### PR TITLE
Add in-depth Duels stats to GraphQL spec

### PR DESCRIPTION
**Pull request by Shqrp**
Hey there,

I added Duels types to the spec. Tell me if everything is correct!

### CODE REVIEW

**Comment by builder-247** [comment]
Thank you for your contribution!

**Comment by builder-247** [comment]
Have you found the GraphQL syntax error?

https://travis-ci.org/github/slothpixel/core/builds/743652902#L388

**Comment by Shqrp** [comment]
Oh, I see! The problem is that I can't use an integer as a field's name in a GraphQL type. I tried searching on the web, but I couldn't find anything, so I ask you (that I'm sure know better me) is it possible to wrap it around quotes, like this?
`
`

**Comment by Shqrp** [comment]
Ok, checked GraphQL Specification, and can confirm a field's name must be a string.
image

Can't use single quote or double-quote either.
image

I just need to thing a solution for this, I may use an array of values, so instead of accessing `Layout.0` it would be `Layout[0]`.
I hope to find a solution. 😅

**Comment by Shqrp** [comment]
Also if you could help me update [spec.js](https://github.com/slothpixel/core/blob/master/routes/spec.js) while I try to find a solution to this, that would be amazing :D

**Comment by builder-247** [comment]
Hey, and thank you again for taking your time to help the project.

Unfortunately I just now realized that Duels stats currently present are only temporary, and are meant to be replaced by https://github.com/slothpixel/core/pull/530, which has been waiting for minor changes for a while.

Could you work on documenting this new format?

**Pull request closed without merging**
